packages:
  - "packages/*"
  - "apps/*"

allowBuilds:
  "@google/genai": true
  better-sqlite3: true
  core-js-pure: true
  esbuild: true
  protobufjs: true
  sharp: true
  workerd: true

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vitest: 5.0.1

update:
  ignoreDeps:
    - typescript

minimumReleaseAge: 1440
