import { routeAgentRequest } from "agents";
import { ChatAgent } from "./src/lib/server/agent/chat-agent";
// @ts-ignore - generated by SvelteKit build
import sveltekit from "./.svelte-kit/cloudflare/_sveltekit.js";

export { ChatAgent };

export default {
  async fetch(request: Request, env: unknown, ctx: ExecutionContext): Promise<Response> {
    const agentResponse = await routeAgentRequest(request, env as Record<string, unknown>);
    if (agentResponse) return agentResponse;
    return (sveltekit as { fetch: typeof fetch }).fetch(request, env, ctx);
  },
} satisfies ExportedHandler;
