import { SVG_CLASSES, SVG_DARK_VARS } from "$lib/chat/svg-styles";

export const FRAME_SHELL = [
  "<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1.0'>",
  "<style>",
  ":root{",
  "--color-text-primary:#e6e3dc;--color-text-secondary:#9a948d;--color-text-tertiary:#736f6a;",
  "--color-text-success:#a8b890;--color-text-warning:#d4b88e;--color-text-danger:#d06464;",
  "--color-text-info:#a3b8c4;",
  "--color-background-primary:#1a1917;--color-background-secondary:#242220;--color-background-tertiary:#332f2c;",
  "--color-background-info:#2a2c2c;--color-background-success:#2b2c26;--color-background-warning:#302c25;--color-background-danger:#302220;",
  "--color-border-primary:rgba(230,227,220,.4);--color-border-secondary:rgba(230,227,220,.3);--color-border-tertiary:rgba(230,227,220,.15);",
  "--color-border-info:#a3b8c4;--color-border-success:#a8b890;--color-border-warning:#d4b88e;--color-border-danger:#d06464;",
  "--color-accent:#d8a0b2;",
  '--font-sans:"Geist","Inter",system-ui,"PingFang SC","Noto Sans SC","Microsoft YaHei",sans-serif;',
  '--font-serif:"Lora","Noto Serif SC","Source Han Serif SC",Georgia,serif;',
  '--font-mono:"Geist Mono","JetBrains Mono","Fira Code",Consolas,Monaco,monospace;',
  "--border-radius-md:5px;--border-radius-lg:7px;--border-radius-xl:10px",
  "}",
  "*{box-sizing:border-box}",
  "html,body{margin:0;padding:0;overflow:hidden;font-family:var(--font-sans);font-size:14px;line-height:1.7;background:var(--color-background-primary);color:var(--color-text-primary)}",
  "button,input,select,textarea{font-family:inherit}",
  ":root{" + SVG_DARK_VARS + "}",
  SVG_CLASSES,
  "</style>",
  "</head><body><div id=root></div>",
  "<script>",
  "var root=document.getElementById('root');",
  "window.addEventListener('message',function(e){",
  "  if(!e.data||typeof e.data!=='object')return;",
  "  if(e.data.type==='setContent'&&typeof e.data.html==='string'){",
  "    root.innerHTML=e.data.html;",
  "  }",
  "  if(e.data.type==='runScripts'){",
  "    document.querySelectorAll('#root script').forEach(function(o){var s=document.createElement('script');if(o.src){s.src=o.src;if(o.onload)s.onload=o.onload;}else{s.textContent=o.textContent}o.parentNode.replaceChild(s,o);});",
  "  }",
  "});",
  "</script>",
  "</body></html>",
].join("");
