import { SVG_CLASSES, SVG_DARK_VARS } from "$lib/visual/svg-styles";

export const FRAME_SHELL = [
  "<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta name=viewport content='width=device-width,initial-scale=1.0'>",
  "<style>",
  ":root{",
  "--color-text-primary:#e6e3dc;--color-text-secondary:#9a948d;--color-text-tertiary:#736f6a;",
  "--color-text-success:#a8b890;--color-text-warning:#d4b88e;--color-text-danger:#d06464;",
  "--color-text-info:#a3b8c4;",
  "--color-background-primary:#1a1917;--color-background-secondary:#242220;--color-background-tertiary:#332f2c;",
  "--color-background-info:#2a2c2c;--color-background-success:#2b2c26;--color-background-warning:#302c25;--color-background-danger:#302220;",
  "--color-border-primary:rgba(230,227,220,.4);--color-border-secondary:rgba(230,227,220,.3);--color-border-tertiary:rgba(230,227,220,.15);",
  "--color-border-info:#a3b8c4;--color-border-success:#a8b890;--color-border-warning:#d4b88e;--color-border-danger:#d06464;",
  "--color-accent:#d8a0b2;",
  '--font-sans:"Geist","Inter",system-ui,"PingFang SC","Noto Sans SC","Microsoft YaHei",sans-serif;',
  '--font-serif:"Lora","Noto Serif SC","Source Han Serif SC",Georgia,serif;',
  '--font-mono:"Geist Mono","JetBrains Mono","Fira Code",Consolas,Monaco,monospace;',
  "--border-radius-md:5px;--border-radius-lg:7px;--border-radius-xl:10px",
  "}",
  "*{box-sizing:border-box}",
  "html,body{margin:0;padding:0;overflow:hidden;font-family:var(--font-sans);font-size:14px;line-height:1.7;background:var(--color-background-primary);color:var(--color-text-primary)}",
  "button,input,select,textarea{font-family:inherit}",
  "@keyframes _in{from{opacity:0}to{opacity:1}}",
  ":root{" + SVG_DARK_VARS + "}",
  SVG_CLASSES,
  "</style>",
  "</head><body><div id=root></div>",
  '<script src="https://cdn.jsdelivr.net/npm/morphdom@2.7.4/dist/morphdom.min.js"></script>',
  "<script>",
  "(function(){",
  'var root=document.getElementById("root");',
  "if(!root)return;",
  "var FADE_IN='_in .3s ease both';",
  "",
  "function applyHTML(html){",
  "  var next=document.createElement(root.tagName.toLowerCase());",
  "  for(var i=0;i<root.attributes.length;i++){",
  "    var a=root.attributes[i];",
  "    if(a.name!=='id')next.setAttribute(a.name,a.value);",
  "  }",
  "  next.innerHTML=html;",
  "  morphdom(root,next,{",
  "    onBeforeElUpdated:function(from,to){return !from.isEqualNode(to);},",
  "    onNodeAdded:function(node){",
  "      if(node.nodeType===1&&node.nodeName!=='STYLE'&&node.nodeName!=='SCRIPT'){",
  "        node.style.animation=FADE_IN;",
  "      }",
  "      return node;",
  "    }",
  "  });",
  "}",
  "",
  "var runningScripts=false,pendingFinal=false;",
  "function runScripts(){",
  "  var scripts=[].slice.call(root.querySelectorAll('script')),i=0;",
  "  !function next(){",
  "    if(i>=scripts.length){runningScripts=false;if(pendingFinal){pendingFinal=false;runScripts();}return;}",
  "    var old=scripts[i++];",
  "    if(!old.parentNode){next();return;}",
  "    var s=document.createElement('script');",
  "    for(var j=0;j<old.attributes.length;j++){var a=old.attributes[j];s.setAttribute(a.name,a.value);}",
  "    if(old.src){",
  "      s.addEventListener('load',function(){next();},{once:true});",
  "      s.addEventListener('error',function(){next();},{once:true});",
  "      old.parentNode.replaceChild(s,old);",
  "    }else{",
  "      s.textContent=old.textContent||'';",
  "      old.parentNode.replaceChild(s,old);",
  "      next();",
  "    }",
  "  }();",
  "}",
  "",
  "var queued=null,domReady=document.readyState!=='loading';",
  "function flushQueued(){",
  "  if(!queued)return;",
  "  var q=queued;queued=null;",
  "  applyHTML(q.html);",
  "  if(q.final){",
  "    if(runningScripts){pendingFinal=true;}",
  "    else{runningScripts=true;runScripts();}",
  "  }",
  "}",
  "window.addEventListener('message',function(e){",
  "  if(!e.data||typeof e.data!=='object')return;",
  "  if(e.data.type!=='content'||typeof e.data.html!=='string')return;",
  "  queued={html:e.data.html,final:!!e.data.final};",
  "  if(domReady)flushQueued();",
  "});",
  "if(!domReady){",
  "  document.addEventListener('DOMContentLoaded',function(){",
  "    domReady=true;",
  "    flushQueued();",
  "  },{once:true});",
  "}",
  "})();",
  "</script>",
  "</body></html>",
].join("");
